webshop_title = {
    "en": "WebShop",
    "zh": "网上商店",
    "fr": "Boutique en ligne",
    "es": "Tienda web",
    "de": "WebShop",
    "el": "WebShop",
    "bg": "Уеб магазин",
    "ru": "Интернет-магазин",
    "tr": "Web Mağazası",
    "ar": "ويب شوب",
    "vi": "WebShop",
    "th": "เว็บช็อป",
    "hi": "वेबशॉप",
    "sw": "WebShop",
    "ur": "ویب شاپ"
}
webshop_instruction = {
    "en": "Instruction",
    "zh": "指令",
    "fr": "Instruction",
    "es": "Instrucción",
    "de": "Anweisung",
    "el": "Εντολή",
    "bg": "Инструкция",
    "ru": "Инструкция",
    "tr": "Talimat",
    "ar": "تعليمات",
    "vi": "Chỉ dẫn",
    "th": "คำแนะนำ",
    "hi": "अनुदेश",
    "sw": "Maagizo",
    "ur": "ہدایت"
}
webshop_search_hint = {
    "en": "Search...",
    "zh": "关键词",
    "fr": "Recherche...",
    "es": "Buscar...",
    "de": "Suchen...",
    "el": "Αναζήτηση...",
    "bg": "Търсене...",
    "ru": "Поиск...",
    "tr": "Aramak...",
    "ar": "يبحث...",
    "vi": "Tìm kiếm...",
    "th": "ค้นหา...",
    "hi": "खोज...",
    "sw": "Tafuta...",
    "ur": "تلاش کریں..."
}
webshop_search = {
    "en": "Search",
    "zh": "搜索",
    "fr": "Recherche",
    "es": "Buscar",
    "de": "Suchen",
    "el": "Αναζήτηση",
    "bg": "Търсене",
    "ru": "Поиск",
    "tr": "Aramak",
    "ar": "يبحث",
    "vi": "Tìm kiếm",
    "th": "ค้นหา",
    "hi": "खोज",
    "sw": "Tafuta",
    "ur": "تلاش کریں۔"
}
webshop_back_btu = {
    "en": "Back to Search",
    "zh": "返回搜索页面",
    "fr": "Retour à la recherche",
    "es": "Volver a la búsqueda",
    "de": "Zurück zur Suche",
    "el": "Επιστροφή στην Αναζήτηση",
    "bg": "Назад към Търсене",
    "ru": "Вернуться к поиску",
    "tr": "Aramaya Geri Dön",
    "ar": "العودة إلى البحث",
    "vi": "Quay lại Tìm kiếm",
    "th": "กลับไปที่การค้นหา",
    "hi": "खोज पर वापस जाएं",
    "sw": "Rudi kwenye Utafutaji",
    "ur": "تلاش پر واپس جائیں۔"
}
webshop_page = {
    "en": "Page",
    "zh": "页面",
    "fr": "Page",
    "es": "Página",
    "de": "Seite",
    "el": "Σελίδα",
    "bg": "Страница",
    "ru": "Страница",
    "tr": "Sayfa",
    "ar": "صفحة",
    "vi": "Trang",
    "th": "หน้าหนังสือ",
    "hi": "पृष्ठ",
    "sw": "Ukurasa",
    "ur": "صفحہ"
}
webshop_total_results = {
    "en": "Total results",
    "zh": "总结果",
    "fr": "Résultats totaux",
    "es": "Resultados totales",
    "de": "Gesamtergebnisse",
    "el": "Συνολικά αποτελέσματα",
    "bg": "Общо резултати",
    "ru": "Всего результатов",
    "tr": "Toplam sonuçlar",
    "ar": "النتائج الإجمالية",
    "vi": "Tổng kết quả",
    "th": "ผลลัพธ์ทั้งหมด",
    "hi": "कुल परिणाम",
    "sw": "Jumla ya matokeo",
    "ur": "کل نتائج"
}
webshop_prev = {
    "en": "Prev",
    "zh": "上一页",
    "fr": "Précédent",
    "es": "Anterior",
    "de": "Zurück",
    "el": "Προηγ",
    "bg": "предишна",
    "ru": "Предыдущий",
    "tr": "Önceki",
    "ar": "السابق",
    "vi": "Trước đó",
    "th": "ก่อนหน้า",
    "hi": "पिछला",
    "sw": "Iliyotangulia",
    "ur": "پچھلا"
}
webshop_next = {
    "en": "Next",
    "zh": "下一页",
    "fr": "Suivant",
    "es": "Próximo",
    "de": "Nächste",
    "el": "Επόμενο",
    "bg": "Следващия",
    "ru": "Следующий",
    "tr": "Sonraki",
    "ar": "التالي",
    "vi": "Kế tiếp",
    "th": "ต่อไป",
    "hi": "अगला",
    "sw": "Inayofuata",
    "ur": "اگلے"
}
webshop_buy = {
    "en": "Buy Now",
    "zh": "现在购买",
    "fr": "Acheter maintenant",
    "es": "Comprar ahora",
    "de": "Kaufe jetzt",
    "el": "Αγορασε τωρα",
    "bg": "Купи сега",
    "ru": "Купить сейчас",
    "tr": "Şimdi al",
    "ar": "اشتري الآن",
    "vi": "Mua ngay",
    "th": "ซื้อเลย",
    "hi": "अभी खरीदें",
    "sw": "Nunua Sasa",
    "ur": "ابھی خریدئے"
}
webshop_price = {
    "en": "Price",
    "zh": "价格",
    "fr": "Prix",
    "es": "Precio",
    "de": "Preis",
    "el": "Τιμή",
    "bg": "Цена",
    "ru": "Цена",
    "tr": "Fiyat",
    "ar": "سعر",
    "vi": "Giá",
    "th": "ราคา",
    "hi": "कीमत",
    "sw": "Bei",
    "ur": "قیمت"
}
webshop_rating = {
    "en": "Rating",
    "zh": "评分",
    "fr": "Notation",
    "es": "Clasificación",
    "de": "Bewertungen",
    "el": "Εκτίμηση",
    "bg": "Рейтинг",
    "ru": "Рейтинг",
    "tr": "Değerlendirme",
    "ar": "تقييم",
    "vi": "Xếp hạng",
    "th": "เรตติ้ง",
    "hi": "रेटिंग",
    "sw": "Ukadiriaji",
    "ur": "درجہ بندی"
}
webshop_description = {
    "en": "Description",
    "zh": "描述",
    "fr": "Description",
    "es": "Descripción",
    "de": "Beschreibung",
    "el": "Περιγραφή",
    "bg": "Описание",
    "ru": "Описание",
    "tr": "Tanım",
    "ar": "وصف",
    "vi": "Sự miêu tả",
    "th": "คำอธิบาย",
    "hi": "विवरण",
    "sw": "Maelezo",
    "ur": "تفصیل"
}
webshop_features = {
    "en": "Features",
    "zh": "特点",
    "fr": "Caractéristiques",
    "es": "Características",
    "de": "Merkmale",
    "el": "Χαρακτηριστικά",
    "bg": "Характеристика",
    "ru": "Функции",
    "tr": "Özellikler",
    "ar": "سمات",
    "vi": "Đặc trưng",
    "th": "คุณสมบัติ",
    "hi": "विशेषताएँ",
    "sw": "Vipengele",
    "ur": "خصوصیات"
}
webshop_reviews = {
    "en": "Reviews",
    "zh": "评论",
    "fr": "Commentaires",
    "es": "Reseñas",
    "de": "Bewertungen",
    "el": "Κριτικές",
    "bg": "Отзиви",
    "ru": "Отзывы",
    "tr": "Yorumlar",
    "ar": "التعليقات",
    "vi": "Đánh giá",
    "th": "รีวิว",
    "hi": "समीक्षा",
    "sw": "Ukaguzi",
    "ur": "جائزے"
}
webshop_attributes = {
    "en": "Attributes",
    "zh": "属性",
    "fr": "Les attributs",
    "es": "Atributos",
    "de": "Eigenschaften",
    "el": "Γνωρίσματα",
    "bg": "Атрибути",
    "ru": "Атрибуты",
    "tr": "Öznitellikler",
    "ar": "صفات",
    "vi": "Thuộc tính",
    "th": "คุณลักษณะ",
    "hi": "गुण",
    "sw": "Sifa",
    "ur": "صفات"
}
webshop_end = {
    "en": "Thank you for shopping with us!",
    "zh": "感谢您来此购物！",
    "fr": "Merci d'avoir fait du shopping avec nous!",
    "es": "gracias por comprar con nosotros!",
    "de": "Danke für ihren Einkauf!",
    "el": "Σας ευχαριστώ για τις αγορές με μας!",
    "bg": "Благодаря, че пазарувахте при нас!",
    "ru": "Спасибо за покупку!",
    "tr": "Bizden alışveriş yaptığınız için teşekkür ederiz!",
    "ar": "شكرا للتسوق معنا!",
    "vi": "Cảm ơn đã đi mua sắm với chúng tôi!",
    "th": "ขอขอบคุณสำหรับการช้อปปิ้งกับเรา!",
    "hi": "हमारे साथ खरीददारी करने के लिए धन्यवाद!",
    "sw": "Asante kwa ununuzi na sisi!",
    "ur": "ہمارے ساتھ خریداری کے لیے آپ کا شکریہ!"
}
webshop_code = {
    "en": "Your code",
    "zh": "您的代码",
    "fr": "Votre code",
    "es": "Tu codigo",
    "de": "Dein Code",
    "el": "Ο κωδικός σου",
    "bg": "Вашият код",
    "ru": "Ваш код",
    "tr": "Senin kodun",
    "ar": "الرمز الخاص بك",
    "vi": "Ma cua ban",
    "th": "รหัสของคุณ",
    "hi": "तुम्हारा कोड",
    "sw": "Msimbo wako",
    "ur": "آپ کا کوڈ"
}
webshop_mturk = {
    "en": "Paste it in your MTurk interface.",
    "zh": "将其粘贴到您的 MTurk 界面中。",
    "fr": "Collez-le dans votre interface MTurk.",
    "es": "Pégalo en tu interfaz MTurk.",
    "de": "Fügen Sie es in Ihre MTurk-Schnittstelle ein.",
    "el": "Επικολλήστε το στη διεπαφή MTurk.",
    "bg": "Поставете го във вашия MTurk интерфейс.",
    "ru": "Вставьте его в свой интерфейс MTurk.",
    "tr": "MTurk arayüzünüze yapıştırın.",
    "ar": "الصقها في واجهة MTurk الخاصة بك.",
    "vi": "Dán nó vào giao diện MTurk của bạn.",
    "th": "วางลงในอินเทอร์เฟซ MTurk ของคุณ",
    "hi": "इसे अपने MTurk इंटरफ़ेस में पेस्ट करें।",
    "sw": "Ibandike kwenye kiolesura chako cha MTurk.",
    "ur": "اسے اپنے MTurk انٹرفیس میں چسپاں کریں۔"
}
webshop_score = {
    "en": "Your score (min 0.0, max 1.0)",
    "zh": "您的分数 (最低 0.0, 最高 1.0)",
    "fr": "Votre score (min 0,0, max 1,0)",
    "es": "Tu puntuación (mínimo 0,0, máximo 1,0)",
    "de": "Ihr Punktestand (mindestens 0,0, maximal 1,0)",
    "el": "Η βαθμολογία σας (ελάχ. 0,0, μέγιστο 1,0)",
    "bg": "Вашият резултат (мин. 0,0, макс. 1,0)",
    "ru": "Ваша оценка (мин. 0,0, макс. 1,0)",
    "tr": "Puanınız (en az 0,0, en fazla 1,0)",
    "ar": "درجاتك (الحد الأدنى 0.0، الحد الأقصى 1.0)",
    "vi": "Điểm của bạn (tối thiểu 0,0, tối đa 1,0)",
    "th": "คะแนนของคุณ (ขั้นต่ำ 0.0, สูงสุด 1.0)",
    "hi": "आपका स्कोर (न्यूनतम 0.0, अधिकतम 1.0)",
    "sw": "Alama yako (dakika 0.0, max 1.0)",
    "ur": "آپ کا سکور (کم سے کم 0.0، زیادہ سے زیادہ 1.0)"
}

def get_price_prompt(price_upper, language):
    webshop_price_prompt = {
        'en': f', and price lower than {price_upper:.2f} dollars',
        'zh': f'价格需要低于{price_upper:.2f}元。',
        'fr': f', et prix inférieur à {price_upper:.2f} dollars',
        'es': f', y precio inferior a {price_upper:.2f} dólares',
        'de': f'und Preis unter {price_upper:.2f} Dollar',
        'el': f', και τιμή χαμηλότερη από {price_upper:.2f} δολάρια',
        'bg': f', и цена по-ниска от {price_upper:.2f} долара',
        'ru': f', и цена ниже {price_upper:.2f} долларов',
        'tr': f've fiyatı {price_upper:.2f} doların altında',
        'ar': f'، وسعر أقل من {price_upper:.2f} دولارًا',
        'vi': f'và giá thấp hơn {price_upper:.2f} đô la',
        'th': f'และราคาต่ำกว่า {price_upper:.2f} ดอลลาร์',
        'hi': f', और कीमत {price_upper:.2f} डॉलर से कम',
        'sw': f', na bei ya chini kuliko dola {price_upper:.2f}',
        'ur': f'، اور قیمت {price_upper:.2f} ڈالر سے کم ہے۔',
    }
    return webshop_price_prompt[language]